### ISSUE TITLE
Java 8 is needed

### ISSUE THREAD

**Issue by 17750669630** [qingmei2/RxWeaver#1]
GlobalErrorTransformer.java
AndroidSchedulers::mainThread

**Comment by qingmei2** [comment]
@17750669630 

我不是太理解您的意思，能否详细阐述一下您遇到的问题？

**Comment by qingmei2** [comment]
因为个人原因，没有更多的精力用于维护Java 分支的代码版本，因此更新以kotlin版本为主。

如果有重大更新，我将会更新对应的Java代码。
